"""Security utilities — password hashing and JWT issuance/verification.

This module centralizes all cryptographic operations:

- Password hashing with bcrypt (via passlib).
- JWT access-token issuance and decoding (via python-jose).

Why centralize:

- Single place to change the algorithm if needed.
- Tests can mock this module instead of every call site.
- Reduces surface area for accidental credential leakage.
"""

from datetime import datetime, timedelta, timezone
from typing import Any

from jose import jwt
from passlib.context import CryptContext

from app.core.config import get_settings

# Bcrypt context shared across the process. Bcrypt initialization is
# expensive — reusing one context is a meaningful performance win.
_pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

# JWT algorithm — HS256 is the standard for symmetric-key JWTs.
JWT_ALGORITHM: str = "HS256"


def hash_password(plain_password: str) -> str:
    """Return a bcrypt hash of the given plaintext password.

    Bcrypt is intentionally slow by design, so callers should not invoke
    this in hot paths — only at signup, password change, and password
    reset.

    Args:
        plain_password: The plaintext password to hash.

    Returns:
        A bcrypt hash string suitable for storage. Includes the salt and
        the algorithm parameters.
    """
    return _pwd_context.hash(plain_password)


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plaintext password against a stored bcrypt hash.

    Args:
        plain_password: The plaintext password the user supplied.
        hashed_password: The hash previously generated by ``hash_password``.

    Returns:
        True if the password matches, False otherwise. Constant-time
        comparison is performed internally by passlib.
    """
    return _pwd_context.verify(plain_password, hashed_password)


def create_access_token(
    subject: str,
    expires_delta: timedelta | None = None,
) -> str:
    """Issue a JWT access token.

    Args:
        subject: The token subject — typically the user's UUID as a string.
        expires_delta: Optional override of the default expiration window.
            If None, uses ``ACCESS_TOKEN_EXPIRE_MINUTES`` from settings.

    Returns:
        An encoded JWT string in compact form, ready for HTTP transport.
    """
    settings = get_settings()

    now = datetime.now(timezone.utc)
    expire = now + (
        expires_delta or timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    )

    payload: dict[str, Any] = {
        "sub": subject,
        "exp": expire,
        "iat": now,
    }

    return jwt.encode(payload, settings.SECRET_KEY, algorithm=JWT_ALGORITHM)


def decode_access_token(token: str) -> dict[str, Any]:
    """Decode and validate a JWT access token.

    Args:
        token: The JWT string from the Authorization header.

    Returns:
        The decoded payload as a dictionary with ``sub``, ``exp``, ``iat``.

    Raises:
        jose.JWTError: If the token is invalid, expired, malformed, or
            its signature does not match.
    """
    settings = get_settings()
    decoded: dict[str, Any] = jwt.decode(
        token, settings.SECRET_KEY, algorithms=[JWT_ALGORITHM]
    )
    return decoded
